#!/bin/bash

source /usr/share/remaster-kit/functions

if [ -e $BUILD_DIR/extract-cd/isolinux ] && [ -e extract-cd/isolinux ]; then
	# Replace isolinux from extract-cd
	sudo rm -r extract-cd/isolinux
	sudo cp -r $BUILD_DIR/extract-cd/isolinux extract-cd/
fi

if [ -e $BUILD_DIR/extract-cd/boot ] && [ -e extract-cd/boot ]; then
	# Replace boot from extract-cd
	sudo rm -r extract-cd/boot
	sudo cp -r $BUILD_DIR/extract-cd/boot extract-cd/
fi

if [ -e $BUILD_DIR/extract-cd/.disk ] && [ -e extract-cd/.disk ]; then
	# Replace .disk from extract-cd
	sudo rm -r extract-cd/.disk
	sudo cp -r $BUILD_DIR/extract-cd/.disk extract-cd/
fi

if [ -e $BUILD_DIR/extract-cd/preseed ] && [ -e extract-cd/preseed ]; then
	# Add preseed from extract-cd
	sudo cp -r $BUILD_DIR/extract-cd/preseed/* extract-cd/preseed/
fi

# Update Initrd on ISO
initrd_name=$(find extract-cd/$VER/ -iname "initrd*")
echo "Updating $initrd_name..."
sudo cp edit/boot/initrd* $initrd_name
